/*************************** Melp***********************/

// ======================= Users Part ======================== //
const GET_USERS_MATCH = 'GET_USERS_MATCH';
const GET_USERS_MATCH_FAIL = 'GET_USERS_MATCH_FAIL';
const GET_USERS_MATCH_SUCCESS = 'GET_USERS_MATCH_SUCCESS';

const CLEAN_USERS_MATCH = 'CLEAN_USERS_MATCH';
const SET_USERS_PAGINATION = 'SET_USERS_PAGINATION';

// =================== Users List Part ==================== //

const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
const UPDATE_USERS_LIST_FAIL = 'UPDATE_USERS_LIST_FAIL';
const UPDATE_USERS_LIST_SUCCESS = 'UPDATE_USERS_LIST_SUCCESS';

// =================== Repositories Part ==================== //
const GET_REPOS_MATCH = 'GET_REPOS_MATCH';
const GET_REPOS_MATCH_FAIL = 'GET_REPOS_MATCH_FAIL';
const GET_REPOS_MATCH_SUCCESS = 'GET_REPOS_MATCH_SUCCESS';

const CLEAN_REPOS_MATCH = 'CLEAN_REPOS_MATCH';
const SET_REPOS_PAGINATION = 'SET_REPOS_PAGINATION';

// =================== Repos Part ==================== //

const UPDATE_REPOS_LIST = 'UPDATE_REPOS_LIST';
const UPDATE_REPOS_LIST_FAIL = 'UPDATE_REPOS_LIST_FAIL';
const UPDATE_REPOS_LIST_SUCCESS = 'UPDATE_REPOS_LIST_SUCCESS';

export {
  CLEAN_REPOS_MATCH,
  CLEAN_USERS_MATCH,
  GET_USERS_MATCH,
  GET_USERS_MATCH_FAIL,
  GET_USERS_MATCH_SUCCESS,
  GET_REPOS_MATCH,
  GET_REPOS_MATCH_FAIL,
  GET_REPOS_MATCH_SUCCESS,
  SET_REPOS_PAGINATION,
  SET_USERS_PAGINATION,
  UPDATE_USERS_LIST,
  UPDATE_USERS_LIST_FAIL,
  UPDATE_USERS_LIST_SUCCESS,
  UPDATE_REPOS_LIST,
  UPDATE_REPOS_LIST_FAIL,
  UPDATE_REPOS_LIST_SUCCESS,
};
