/*************************** TAUROS ***********************/
const GET_BALANCES_LIST = 'pages/home/GET_BALANCES_LIST';
const GET_BALANCES_LIST_ERROR = 'pages/home/GET_BALANCES_LIST_ERROR';
const GET_BALANCES_LIST_SUCCESS = 'pages/home/GET_BALANCES_LIST_SUCCESS';

export { GET_BALANCES_LIST, GET_BALANCES_LIST_ERROR, GET_BALANCES_LIST_SUCCESS };
